const accordion: Instrument =
    new Instrument('accordion',
        [   "a3",
            "a#3",
            "b3",
            "c4",
            "c#4",
            "d4",
            "d#4",
            "e4",
            "f4",
            "f#4",
            "g4",
            "g#4",
            "a4",
            "a#4",
            "b4",
            "c5",
            "c#5",
            "d5",
            "d#5",
            "e5",
            "f5",
            "f#5",
            "g5",
            "g#5",
            "a5",],
        4,
        "#8B331D",
        MeasureCategory.Melody)