const accordion: Instrument =
    new Instrument('accordion',
        [   "accordion/a3",
            "accordion/a#3",
            "accordion/b3",
            "accordion/c4",
            "accordion/c#4",
            "accordion/d4",
            "accordion/d#4",
            "accordion/e4",
            "accordion/f4",
            "accordion/f#4",
            "accordion/g4",
            "accordion/g#4",
            "accordion/a4",
            "accordion/a#4",
            "accordion/b4",
            "accordion/c5",
            "accordion/c#5",
            "accordion/d5",
            "accordion/d#5",
            "accordion/e5",
            "accordion/f5",
            "accordion/f#5",
            "accordion/g5",
            "accordion/g#5",
            "accordion/a5",],
        4,
        "#8B331D",
        MeasureCategory.Melody)