const bass: Instrument =
    new Instrument('bass',
        [   "a2",
            "a#2",
            "b2",
            "c3",
            "c#3",
            "d3",
            "d#3",
            "e3",
            "f3",
            "f#3",
            "g3",
            "g#3",
            "a3",
            "a#3",
            "b3",
            "c4",
            "c#4",
            "d4",
            "d#4",
            "e4",
            "f4",
            "f#4",
            "g4",
            "g#4",
            "a4"],
        3,
        "#2E149A",
        MeasureCategory.Harmony)