const caixa: Instrument =
    new Instrument('caixa',
        [   "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",],
        null,
        "#E49885",
        MeasureCategory.Rhythm)