const drop: Instrument =
    new Instrument('drop',
        ["drop/1",
            "drop/2",
            "drop/3",
            "drop/4",
            "drop/5",
            "drop/6",
            "drop/7",
            "drop/8",
            "drop/9",
            "drop/10",
            "drop/11",
            "drop/12",
            "drop/13",
            "drop/14",
            "drop/15",
            "drop/17",
            "drop/18",
            "drop/19",
            "drop/20",
            "drop/21",
            "drop/22",
            "drop/23",
        ],
        null,
        "#E49885",
        MeasureCategory.Rhythm)