const funkKick: Instrument =
    new Instrument('funk_kick',
        [   "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10"],
        null,
        "#380B3F",
        MeasureCategory.Rhythm)