const funkVoice: Instrument =
    new Instrument('funk_voice',
        [   "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11"],
        null,
        "#5B401A",
        MeasureCategory.Rhythm)