const funkHighPercussion: Instrument =
    new Instrument('funk_high_percussion',
        [   "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11"],
        null,
        "#380B3F",
        MeasureCategory.Rhythm)