const funkVoice: Instrument =
    new Instrument('funk_voice',
        ["funk_voice/1",
            "funk_voice/2",
            "funk_voice/3",
            "funk_voice/4",
            "funk_voice/5",
            "funk_voice/6",
            "funk_voice/7",
            "funk_voice/8",
            "funk_voice/9",
            "funk_voice/10",
            "funk_voice/11"],
        null,
        "#380B3F",
        MeasureCategory.Rhythm)