const hihat: Instrument =
    new Instrument('hihat',
        ["hihat/1",
            "hihat/2",
            "hihat/3",
            "hihat/4",
            "hihat/5",
            "hihat/6",
            "hihat/7",
            "hihat/8",
            "hihat/9",
            "hihat/10"],
        null,
        "#380B3F",
        MeasureCategory.Rhythm)