const vibraslap: Instrument =
    new Instrument('vibraslap',
        [   "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12"],
        null,
        "#380B3F",
        MeasureCategory.Rhythm)