const xylo: Instrument =
    new Instrument('xylo',
        [   "a4",
            "a5",
            "b4",
            "c4",
            "c5",
            "d4",
            "d5",
            "e4",
            "e5",
            "f4",
            "f5", 
            "g4",
            "g5"],
        null,
        "#BA8DC3",
        MeasureCategory.Rhythm)